#!/bin/sh
echo " " 
echo "*******************************"   
echo ""                                                    
echo " DuskyFHD skin successful installed...  "
echo ""
echo " ...now select skin DuskyFHD..." 
echo ""
echo "*******************************"   
echo " "                                                       
exit 0
