#!/bin/sh
rm -rf /usr/share/enigma2/DuskyFHD
echo " " 
echo "*******************************" 
echo " "                                                         
echo "  skin successful removed...  "
echo " "    
echo "*******************************" 
echo " "  
exit 0                                               
