#!/bin/sh
echo " " 
echo "*******************************"   
echo ""                                                    
echo "           Nacht skin successful installed...  "
echo ""
echo "              select your skin Nacht..." 
echo ""
echo "*******************************"   
echo " "                                                       
exit 0
