#!/bin/sh
rm -rf /usr/share/enigma2/LiteHD2
echo " " 
echo "*******************************" 
echo " "                                                         
echo "             skin successful removed...  "
echo " "    
echo "                 restart gui now..."      
echo " "   
echo "*******************************" 
echo " "  
exit 0                                               
